In [2]:
import numpy as np #for array

In [3]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [4]:
type(a) #nd=n dimensional 

numpy.ndarray

In [5]:
a2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
a3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [7]:
print(a2.shape)#for rows and columns
print(a2.ndim)
print(a2.dtype)

(2, 5)
2
int64


In [8]:
np.arange(10)
#np.arange(1,11)
#np.arange(1,11,2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.random.randint(1,11,size=(2,3))

array([[6, 6, 6],
       [7, 1, 8]], dtype=int32)

In [10]:
x=np.array([[7,2,3],[2,5,2],[3,5,1]])
y=np.array([[1,8,3],[3,7,2],[2,5,3]])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


In [11]:
print(x*y)

[[ 7 16  9]
 [ 6 35  4]
 [ 6 25  3]]


In [12]:
print(x@y) #matrix multiplication

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [13]:
np.dot(x,y)   #matrix multiplication

array([[19, 85, 34],
       [21, 61, 22],
       [20, 64, 22]])

In [14]:
x.prod()  #product of all elements in array

np.int64(12600)

In [15]:
x.mean()   #mean of all elements

np.float64(3.3333333333333335)

In [16]:
x.mean(axis=0)   #column wise mean

array([4., 4., 2.])

In [17]:
y.mean(axis=1)   #row wise mean

array([4.        , 4.        , 3.33333333])

In [18]:
print(x.sum())
print(x.std())   #ui library ppt other than flask,streamlit(usko use krke fir kuch bnana hai)
print(x.var())

30
1.8257418583505538
3.3333333333333335


In [19]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,25)) #1st quartile
print(np.percentile(a,50))  #median
print(np.percentile(a,75))  #3rd quartile

3.0
5.0
7.0


In [20]:
b=np.random.randint(11,100,(4,4))
print(b)

[[21 79 56 58]
 [85 47 37 33]
 [19 27 78 53]
 [11 37 67 54]]


In [21]:
print('2X8')
print(b.reshape(2,8)) #cannot reshape array of size like eg 3x4 into 2,8
print('8X2')
print(b.reshape(8,2))

2X8
[[21 79 56 58 85 47 37 33]
 [19 27 78 53 11 37 67 54]]
8X2
[[21 79]
 [56 58]
 [85 47]
 [37 33]
 [19 27]
 [78 53]
 [11 37]
 [67 54]]


In [22]:
x=np.random.randint(1,11,(5,5))
print(x)

[[ 3  9  4 10  1]
 [ 3  6  1  1  6]
 [ 5  7  6  1  4]
 [ 8  7  2  8  1]
 [10  1  7  5  7]]


In [23]:
print(x[0])   #1st row
print(x[0,1])  #1st row and 2nd columnn's first element
print(x[-1])

print(x[:3])
print(x[3:])

[ 3  9  4 10  1]
9
[10  1  7  5  7]
[[ 3  9  4 10  1]
 [ 3  6  1  1  6]
 [ 5  7  6  1  4]]
[[ 8  7  2  8  1]
 [10  1  7  5  7]]
